Implementation based on binary search over a pre-sorted list of CIDRs
libp2p/go-libp2p-asn-util pull request #8
Opened 2020-08-27 22:04 UTC by petar

2020-09-02 17:01 UTC, aschmahmann commented on asn.go
> +	Store = &store{m}
I suspect we're still better off with an indirect store here where we unmarshal either on first use or in a goroutine.

2020-09-02 23:15 UTC, aschmahmann requested changes
Overall seems reasonable. More comments would be helpful to be better understand + audit the code. Also it seems like a lot of this is shared with go-libp2p-xor as mentioned in one of my comments above. Is there a reason the code shouldn't be shared?

2020-09-02 23:15 UTC, aschmahmann commented on asn.go
> +	Store = &store{m}
I suspect we're still better off with an indirect store here where we unmarshal either on first use or in a goroutine.

2020-09-02 23:15 UTC, aschmahmann commented on asn_test.go
> +}
Is this just testing the init function works? If so add some comments and do some verification on the Store

2020-09-02 23:15 UTC, aschmahmann commented on generate/main.go
> +	printf("var cidrASNRaw = %s", strconv.Quote(string(data)))
This is a really inefficient way to store the data in text. Each byte turns into 4 bytes (0xFF is one byte but is represent as the string "\xFF" which is 4 bytes. Does it effect binary size as well or does Go do a good job just turning the whole thing into a byte array? e.g. how big is a blank binary with/without this being included?

If the binary size isn't really effected then :shrug:, but if it is then we may want to consider a more compact form including https://github.com/go-bindata/go-bindata, or being a little more low level by using some base encoding and/or gzipping the data. It may take slightly longer to load but if it decreases the binary size substantially then it might be worth it.

2020-09-02 23:15 UTC, aschmahmann commented on trie/cidrasn.go
> +	// "go.mongodb.org/mongo-driver/bson"
remove?

2020-09-02 23:15 UTC, aschmahmann commented on trie/add.go
> +	// q.Len() > depth
leftover code or a comment?

2020-09-02 23:15 UTC, aschmahmann commented on trie/add.go
> +				// trie.Key.Len() > depth
leftover code or a comment?

2020-09-02 23:15 UTC, aschmahmann commented on trie/add.go
> +			} else { // trie.Key.Len() > depth
leftover code or a comment?

2020-09-02 23:15 UTC, aschmahmann commented on trie/add.go
> +package trie
This looks largely copied from go-libp2p-xor, or am I missing something?

2020-09-02 23:15 UTC, aschmahmann commented on trie/find.go
> +			return depth, []*Key{trie.Key}
If the leaf is 0010 and the key is 0001 why is the leaf considered a subkey? Or perhaps I've misunderstood this given the comment above:

> finds all keys in the trie that are prefixes of the query key.

2020-09-02 23:15 UTC, aschmahmann commented on trie/numbers.go
> +type Sup Number
Add some clarity on what these mean/what their differences are (I'm guessing Subscript and Superscript based on some Trie notation, but more info would be helpful for myself and future readers)

2020-09-02 23:15 UTC, aschmahmann commented on trie/numbers.go
> +}
Probably need to either document how we're setting the bits or clarify that while `Bytes` is public it's not to be modified by others (i.e. it's just an easy way to serialize/deserialize the data)

2020-09-02 23:15 UTC, aschmahmann commented on trie/numbers.go
> +		}
You're probably better off xoring a[0] and b[0] and then using `bits.LeadingZeros8` it's easier to read and is probably a tiny bit faster too (it uses a lookup table instead of a loop).

2020-09-02 23:15 UTC, aschmahmann commented on trie/numbers.go
> +// Prev returns the largest number smaller than l.
What's supposed to be going on here? It looks like this turns 1000 into 0000.

2020-09-02 23:15 UTC, aschmahmann commented on trie/numbers.go
> +func Next(u Sup) Sub {
Comment needed

2020-09-02 23:15 UTC, aschmahmann commented on trie/numbers.go
> +func SubLess(xsub, ysub Sub) bool {
comment needed

2020-09-02 23:15 UTC, aschmahmann commented on trie/numbers.go
> +func SupLess(xsup, ysup Sup) bool {
comment needed

2020-09-02 23:15 UTC, aschmahmann commented on trie/numbers.go
> +func SupSubLess(xsup Sup, ysub Sub) bool {
comment needed

2020-09-02 23:15 UTC, aschmahmann commented on trie/numbers.go
> +func SupLess(xsup, ysup Sup) bool {
Also, looks like we could share the code from SubLess and SupLess if instead we had SubLess and SupMore. Would we be losing anything there or making anything more complicated?

2020-09-03 03:30 UTC, petar commented on trie/add.go
> +	// q.Len() > depth
This explicitly states what invariant is true at this point in the code. I've made the comments more explicit.

2020-09-03 03:44 UTC, petar commented on trie/add.go
> +package trie
The data structure and the overall structure of Add was copied. However, the modifications are substantial in that this trie here supports variable-length keys (and to do so allows storage of keys on intermediate nodes). I opted for copying the code for now, as changing the original go-libp2p-xor would have required updating all methods there. The latter is a significant task, as Remove() and shrink() are tricky and would require more work and testing. For the application here, we only need Add and Find. I've created an issue https://github.com/libp2p/go-libp2p-xor/issues/10 to reconcile the two and update go-libp2p-xor.

2020-09-03 04:04 UTC, petar commented on trie/numbers.go
> +		}
This implementation is copied from the Go's internal implementation of the net package. Let's keep it as is for now. Speed is not relevant in this use case, as it is used only during generation.

2020-09-03 04:20 UTC, petar commented on trie/numbers.go
> +// Prev returns the largest number smaller than l.
It turns 1000 into 01111111...., which is the previous number when the bit strings are viewed as real numbers (which I documented now).

2020-09-03 04:26 UTC, petar commented on trie/numbers.go
> +func SupLess(xsup, ysup Sup) bool {
I think the code cannot be shared. But let's see what you think after you read my added comments on what Number, Sub and Sup are. I think the currently under-documented state of the code is causing a misunderstanding of what this does.

2020-09-03 04:30 UTC, petar commented on trie/find.go
> +			return depth, []*Key{trie.Key}
You cannot have key 0001 on leaf 0010. The leaf path must always be a prefix of the key.

2020-09-03 04:32 UTC, petar commented on generate/main.go
> +	printf("var cidrASNRaw = %s", strconv.Quote(string(data)))
It is not affected :) Go places the string's binary representation in the linked binary. It doesn't matter how you represent it in syntax.

2023-12-19 13:28 UTC, closed without merging